FROM microsoft/dotnet:2.1.1-aspnetcore-runtime AS base

#Add NodeJS
#RUN apt-get update && \
#    apt-get install -y wget && \
#    apt-get install -y gnupg2 && \
#    wget -qO- https://deb.nodesource.com/setup_8.x | bash - && \
#    apt-get install -y build-essential nodejs && \
#	  rm -rf /var/lib/apt/lists/*

ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/nodejs

WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["Edison.Web/Edison.AdminPortal/Edison.AdminPortal.csproj", "Edison.Web/Edison.AdminPortal/"]
RUN dotnet restore "Edison.Web/Edison.AdminPortal/Edison.AdminPortal.csproj"
COPY . .
WORKDIR "/src/Edison.Web/Edison.AdminPortal"

#Add NodeJS
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y build-essential nodejs && \
	  rm -rf /var/lib/apt/lists/*

#RUN dotnet build "Edison.AdminPortal.csproj" -c Debug -o /app

#FROM build AS publish
RUN dotnet publish "Edison.AdminPortal.csproj" -c Debug -o /app

FROM base AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Edison.AdminPortal.dll"]
