
export type IconType =
    'chat'
    | 'sensors'
    | 'now'
    | 'shield'
    | 'location-circle'
    | 'history'
    | 'gear'
    | 'location'
    | 'location-blue'
    | 'arrow-down'
    | 'arrow-up'
    | 'horn'
    | 'horn-lightblue'
    | 'fire'
    | 'gun'
    | 'health'
    | 'package'
    | 'pollution'
    | 'protest'
    | 'tornado'
    | 'vip'
    | 'search'
    | 'shield-plain'
    | 'notification'
    | 'light'
    | 'close'
    | 'expand'
    | 'reload'
    | 'button'
    | 'sound'
    | 'message'
    | 'zoomIn'
    | 'zoomOut'
    | 'edit'
    | 'time'
    | 'stairs'
    | 'building'
    | 'person'
    | 'dot';

export type IconSize =
    'tiny'
    | 'small'
    | 'medium-small'
    | 'medium'
    | 'large-medium'
    | 'large'
    | 'extra-large';
